# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha3
    name: e2e-v1alpha3
    job_types:
      - presubmit
    include_dirs:
    - pkg/apis/controller/common/v1alpha3/*
    - pkg/apis/controller/experiments/v1alpha3/*
    - pkg/apis/controller/trials/v1alpha3/*
    - pkg/apis/controller/suggestions/v1alpha3/*
    - pkg/apis/controller/*.go
    - pkg/apis/manager/health/*
    - pkg/apis/manager/v1alpha3/*
    - pkg/common/v1alpha3/*
    - pkg/controller.v1alpha3/*
    - pkg/db/v1alpha3/*
    - pkg/job/v1alpha3/*
    - pkg/metricscollector/v1alpha3/*
    - pkg/suggestion/v1alpha3/*
    - pkg/ui/v1alpha3/*
    - pkg/util/v1alpha3/*
    - pkg/webhook/v1alpha3/*
    - cmd/db-manager/v1alpha3/*
    - cmd/katib-controller/v1alpha3/*
    - cmd/metricscollector/v1alpha3/*
    - cmd/suggestion/chocolate/v1alpha3/*
    - cmd/suggestion/hyperband/v1alpha3/*
    - cmd/suggestion/hyperopt/v1alpha3/*
    - cmd/suggestion/nasrl/v1alpha3/*
    - cmd/suggestion/skopt/v1alpha3/*
    - cmd/suggestion/goptuna/v1alpha3/*
    - cmd/ui/v1alpha3/*
    - examples/v1alpha3/*.yaml
    - test/e2e/v1alpha3/*
    - test/scripts/v1alpha3/*
    - test/workflows/*
    - manifests/v1alpha3/*
    - scripts/v1alpha3/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-ci"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha3
    name: e2e-v1alpha3
    job_types:
      - postsubmit
    include_dirs:
    - pkg/apis/controller/common/v1alpha3/*
    - pkg/apis/controller/experiments/v1alpha3/*
    - pkg/apis/controller/trials/v1alpha3/*
    - pkg/apis/controller/suggestions/v1alpha3/*
    - pkg/apis/controller/*.go
    - pkg/apis/manager/health/*
    - pkg/apis/manager/v1alpha3/*
    - pkg/common/v1alpha3/*
    - pkg/controller.v1alpha3/*
    - pkg/db/v1alpha3/*
    - pkg/job/v1alpha3/*
    - pkg/metricscollector/v1alpha3/*
    - pkg/suggestion/v1alpha3/*
    - pkg/ui/v1alpha3/*
    - pkg/util/v1alpha3/*
    - pkg/webhook/v1alpha3/*
    - cmd/db-manager/v1alpha3/*
    - cmd/katib-controller/v1alpha3/*
    - cmd/metricscollector/v1alpha3/*
    - cmd/suggestion/chocolate/v1alpha3/*
    - cmd/suggestion/hyperband/v1alpha3/*
    - cmd/suggestion/hyperopt/v1alpha3/*
    - cmd/suggestion/nasrl/v1alpha3/*
    - cmd/suggestion/skopt/v1alpha3/*
    - cmd/suggestion/goptuna/v1alpha3/*
    - cmd/ui/v1alpha3/*
    - examples/v1alpha3/*.yaml
    - test/e2e/v1alpha3/*
    - test/scripts/v1alpha3/*
    - test/workflows/*
    - manifests/v1alpha3/*
    - scripts/v1alpha3/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-images-public"
